#!/usr/bin/env bash
# configures an Nginx server so that /redirect_me is redirecting to another page

apt-get update
apt-get install -y nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello Word!" > /etc/nginx/html/index.html
printf %s "server {
    listen 80;
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" > /etc/nginx/sites-available/default
echo "server {
    listen 80;
    listen [::]:80;

    root /var/www/html;

    # Add index.php to the list if you are using PHP
    index index.html index.htm index.nginx-debian.html;

    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}" | sudo tee /etc/nginx/sites-available/redirect

# Enable the new site configuration
sudo ln -s /etc/nginx/sites-available/redirect /etc/nginx/sites-enabled/


# Test Nginx configuration and reload
sudo nginx -t
sudo service nginx reload

